#!/usr/bin/env python3

"""
DynaCLI bootstrap script # Change me
"""


import os
import sys
from typing import Final

cwd = os.path.dirname(os.path.realpath(__file__))

__version__: Final[str] = "0.0.0" # Change me to define your own version

from dynacli import main

search_path = [cwd] # Change me if you have different path
sys.path.extend(search_path)

main(search_path)
