#!/usr/bin/env python3
"""
Greetings CLI
"""

import sys
import os
from typing import Final

from dynacli import main

cwd = os.path.dirname(os.path.realpath(__file__))

__version__: Final[str] = "1.0"

search_path = [cwd]
sys.path.extend(search_path)

main(search_path)