#!/usr/bin/env python3

"""
Sample DynaCLI Tool without root package
"""

import os
import sys

cwd = os.path.dirname(os.path.realpath(__file__))
base, _, _ = cwd.partition('/test')
sys.path.append(f'{base}/src/dynacli')
__version__ = "02.1"

from dynacli import main

search_path = [f'{cwd}/storage_X/cli/dev']
sys.path.extend(search_path)

main(search_path)
