#!/usr/bin/env python3

"""
Sample DynaCLI Tool
"""

import os
import sys

cwd = os.path.dirname(__file__)
base, _, _ = cwd.partition('/test')
sys.path.append(f'{base}/src/python')
__version__ = "22.2"

from dynacli import main

search_path = [f'{cwd}/storage_X/', f'{cwd}/storage_Y/']
root_packages = ['cli.dev']
sys.path.extend(search_path)

main(search_path, root_packages)
