name: Test
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  test:
    name: test py${{ matrix.python-version }} on linux
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9.6']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install flit==3.6.0
      - run: flit install
      - run: cd test/integrated; python3 -m unittest test_dynacli.py
