name: Test
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64
      - run: pip install flit==3.6.0
      - run: flit install
      - run: cd test/integrated; python3 -m unittest test_dynacli.py
